DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
  id INT GENERATED ALWAYS AS IDENTITY,
  nama VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  tanggal_registrasi TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id) 
);

DROP TABLE IF EXISTS alumni CASCADE;
CREATE TABLE alumni(
  id INT GENERATED ALWAYS AS IDENTITY,
  nisn VARCHAR(50) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  jenis_kelamin VARCHAR(50) NOT NULL,
  tempat_lahir VARCHAR(50) NOT NULL,
  tanggal_lahir DATE NOT NULL,
  tahun_lulus VARCHAR(5) NOT NULL,
  alamat VARCHAR(255),
  no_hp VARCHAR(50),
  email VARCHAR(50),
  PRIMARY KEY(id) 
);

