import NavBar from '../components/Navbar'

const InfoPelatihan = () => {
  return (
    <>
      <NavBar />
      <div className="row mt-5 px-5">
        <div className="col-lg-8">
          {/* the actual blog post: title/author/date/content */}
          <h1><a href>Pelatihan Membuat CV yang baik</a></h1>
          <p className="lead"><i className="fa fa-user" /> oleh <a href>Admin</a>
          </p>
          <hr />
          <p><i className="fa fa-calendar" /> Di Publis pada 3 Juli 2019 at 9:00 PM</p>
          <p><i className="fa fa-tags" /> Tags: <a href><span className="badge badge-primary">Pelatihan</span></a></p>
          <hr />
          <img src="http://placehold.it/900x300" className="img-responsive" />
          <hr />
          

<div>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Saat melamar pekerjaan, secara tidak langsung kamu sedang “jual diri” di depan perusahaan. Perusahaan melihat CV sebagai bahan pertimbangan sebelum mempekerjakanmu. Maka dari itu, Pinters harus tahu cara membuat CV yang menarik di mata tim HRD.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>HRD biasanya hanya sekilas saat melihat CV. Jika CV mu membosankan dengan terlalu banyak informasi atau narasi tidak penting, usahamu membuat CV akan sia-sia. CV mu pasti langsung di skip.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Rekomendasi Artikel :&nbsp;<a href="https://pintek.id/blog/contoh-surat-lamaran-kerja/" rel="noopener" style={{boxSizing: 'inherit', backgroundColor: 'transparent', color: 'rgb(43, 64, 152)', textDecoration: 'none'}} target="_blank"><strong style={{boxSizing: 'inherit', fontWeight: 'bolder'}}>Dijamin Lolos Seleksi HRD, Begini Contoh Surat Lamaran Kerja Yang Benar</strong></a></p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Ada beberapa cara membuat CV lamaran kerja menarik, supaya tim HRD perusahaan bisa stay dan lebih memperhatikan isi CV mu.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Berikut ini adalah cara membuat cv yang menarik, yang bisa kamu ikuti.</p>
  <h3 style={{boxSizing: 'inherit', marginTop: 0, fontWeight: 700, fontSize: '1.722em', lineHeight: '1.258em', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>1. Hanya Tuliskan Komponen CV yang Perlu</h3>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Dalam sebuah CV ada sejumlah komponen informasi yang ditunjukan. CV harus efektif dalam menyampaikan informasi yang dibutuhkan HRD. Secara umum, ini dia hal yang harus kamu tulis dalam CV lamaran kerja.</p>
  <ul style={{boxSizing: 'inherit', margin: '0px 0px 1.5em 0.5em', listStyle: 'disc', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>
    <li style={{boxSizing: 'inherit'}}>Identitas</li>
  </ul>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Untuk lamaran pekerjaan secara umum, cukup sampaikan nama lengkap dan alamat. Tidak perlu menyampaikan informasi data diri yang berlebihan atau bertele-tele.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Kamu bisa menginformasikan tentang TTL, Berat Badan, Tinggi Badan jika pihak perusahaan memang mempersyaratkan hal-hal tersebut dalam lamaran pekerjaan.</p>
  <ul style={{boxSizing: 'inherit', margin: '0px 0px 1.5em 0.5em', listStyle: 'disc', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>
    <li style={{boxSizing: 'inherit'}}>Kontak</li>
  </ul>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Tuliskan nomor HP aktif yang bisa menerima telepon.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Tuliskan juga alamat email yang bisa kamu akses. Usahakan nama emailnya tampak profesional.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Kamu bisa juga menyampaikan akun social media yang aktif digunakan. Terlebih lagi jika pekerjaan yang kamu lamar berhubungan dengan dunia digital.</p>
  <ul style={{boxSizing: 'inherit', margin: '0px 0px 1.5em 0.5em', listStyle: 'disc', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>
    <li style={{boxSizing: 'inherit'}}>Informasi Pendidikan</li>
  </ul>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Tuliskan hanya pendidikan terakhir, berikut jurusan dan IPKnya.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Selain mencantumkan pendidikan formal, kamu juga bisa menuliskan kursus yang pernah kamu ikuti. Hal tersebut bisa meningkatkan nilai CV mu di mata HRD.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Jika ada banyak kursus yang kamu lakukan, pilih yang relevan atau beberapa kursus yang terakhir kamu ikuti.</p>
  <ul style={{boxSizing: 'inherit', margin: '0px 0px 1.5em 0.5em', listStyle: 'disc', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>
    <li style={{boxSizing: 'inherit'}}>Profil Singkat</li>
  </ul>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Pinters bisa mendeskripsikan diri dengan narasi singkat. Dalam narasi ini, kamu bisa menyampaikan informasi tentang bidang yang kamu geluti, skill, passion, dll.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Mengingat hanya berupa narasi singkat, tuliskan hanya hal penting yang ingin kamu tonjolkan.<br style={{boxSizing: 'inherit'}} />Contoh:</p>
  <div className="code-block code-block-1" style={{boxSizing: 'inherit', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial', margin: '8px 0px 8px 15px', float: 'right'}}><a href="https://pintek.id/pintek-regular/?utm_source=blog&utm_medium=faux%20ads&utm_campaign=register" style={{boxSizing: 'inherit', backgroundColor: 'transparent', color: 'rgb(43, 64, 152)', textDecoration: 'none'}} target="_blank"><img src="https://pintek.id/blog/wp-content/uploads/2020/09/ADS-1-revisi.jpg" width={250} height={250} style={{boxSizing: 'inherit', maxWidth: '100%', height: 'auto', borderStyle: 'none', borderRadius: 8}} /></a></div>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>“Marketing director, berpengalaman di bidang pemasaran dan penjualan selama 10 tahun. Handal dalam membuat dan menerapkan kebijakan pemasaran, terbukti berhasil meningkatkan penjualan hingga 35%. Memiliki keterampilan yang baik dalam manajemen dan interpersonal”</p>
  <ul style={{boxSizing: 'inherit', margin: '0px 0px 1.5em 0.5em', listStyle: 'disc', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>
    <li style={{boxSizing: 'inherit'}}>Skill</li>
  </ul>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Tuliskan beberapa skill yang relevan dengan pekerjaan yang ingin dilamar. Supaya menarik, setiap skill biasanya ditunjukan dalam bentuk graphic statistik sederhana yang menunjukan level atau tingkatan.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Biasanya menggunakan rating bintang, diagram, atau hal lain yang bisa menunjukan level/tingkatan.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Contoh:</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}><img className="aligncenter wp-image-2794 size-full" src="https://pintek.id/blog/wp-content/uploads/2020/10/Langsung-Dilirik-Ini-5-Cara-Membuat-CV-Menarik-di-Mata-HRD-3.png" alt="contoh cv menarik" width={219} height={154} srcSet="https://pintek.id/blog/wp-content/uploads/2020/10/Langsung-Dilirik-Ini-5-Cara-Membuat-CV-Menarik-di-Mata-HRD-3.png 219w, https://pintek.id/blog/wp-content/uploads/2020/10/Langsung-Dilirik-Ini-5-Cara-Membuat-CV-Menarik-di-Mata-HRD-3-130x90.png 130w" sizes="(max-width: 219px) 100vw, 219px" style={{margin: '0 auto', display: 'block', boxSizing: 'inherit', maxWidth: '100%', height: 'auto', borderStyle: 'none', clear: 'both', textAlign: 'center', borderRadius: 8}} /></p>
  <ul style={{boxSizing: 'inherit', margin: '0px 0px 1.5em 0.5em', listStyle: 'disc', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>
    <li style={{boxSizing: 'inherit'}}>Pengalaman Kerja</li>
  </ul>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Pilih pengalaman kerja yang sekiranya relevan. Jika memiliki banyak pengalaman kerja, tuliskan yang durasinya cukup lama atau tuliskan beberapa pengalaman kerja terakhir.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Pinters juga bisa menuliskan sejumlah proyek yang pernah dikerjakan jika memiliki relevansi dengan pekerjaan yang ingin kamu lamar.</p>
  <ul style={{boxSizing: 'inherit', margin: '0px 0px 1.5em 0.5em', listStyle: 'disc', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>
    <li style={{boxSizing: 'inherit'}}>Informasi Lain</li>
  </ul>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Beberapa informasi lain yang bisa dituliskan untuk membuat CV lebih menarik misalnya: kontak referensi dari tempat kerja sebelumnya, pengalaman organisasi, interest/hobi yang relevan dengan pekerjaan, prestasi kerja, dll.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Jika memang tidak ada yang relevan, lebih baik tidak usah dicantumkan.</p>
  <h3 style={{boxSizing: 'inherit', marginTop: 0, fontWeight: 700, fontSize: '1.722em', lineHeight: '1.258em', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>2. Tonjolkan Skill, Pengalaman Kerja, Prestasi Kerja</h3>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Dalam CV, 3 informasi inilah yang seharusnya kamu tonjolkan. Ke-3 informasi tersebut jadi tolok ukur terhadap kemampuan kerjamu. Semakin meyakinkan informasi mengenai skill, pengalaman kerja, dan prestasi kerja yang kamu miliki, HRD akan semakin tertarik untuk merekrutmu.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Jika pengalaman kerjamu belum terlalu banyak, atau belum ada sama sekali, kamu bisa menonjokan skill. Ikut sejumlah kursus adalah salah satu cara meningkatkan skill.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Jika dana jadi kendala, kamu bisa memanfaatkan pinjaman pendidikan dari Pintek. Pinjaman Pintek ini bisa digunakan untuk membiayai sekolah, kuliah, maupun kursus.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Kamu bisa mengajukan pinjaman online ke Pintek langsung melalui&nbsp;<a href="https://pintek.id/" rel="noopener noreferrer" style={{boxSizing: 'inherit', backgroundColor: 'transparent', color: 'rgb(43, 64, 152)', textDecoration: 'none'}} target="_blank">websitenya</a>.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Dengan ikut kursus, kamu bisa mencantumkan skill-skill tambahan di CV. Keikutsertaan terhadap kursus tersebut juga bisa dicantumkan dalam informasi pendidikan non formal.</p>
  <h3 style={{boxSizing: 'inherit', marginTop: 0, fontWeight: 700, fontSize: '1.722em', lineHeight: '1.258em', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>3. Gunakan Desain yang Menarik tapi Tetap Elegan</h3>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Sebelum melihat isinya, seorang HRD pasti melihat penampakan dari CV terlebih dahulu. Maka dari itu desain jadi hal penting yang harus kamu perhatikan juga.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Perhatikan komposisi warnanya, jangan terlalu banyak menggunakan warna. Pilih warna yang tidak terlalu mencolok. Pastikan juga warna yang kamu gunakan tetap membuat tulisan mudah terbaca.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Pilihan font juga wajib kamu perhatikan. Pilih font yang tampak elegan dan tetap mudah terbaca.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Penyusunan setiap elemen informasi juga perlu kamu perhatikan. Pastikan setiap informasi tersampaikan dengan baik. Jangan lupa untuk menonjolkan skill, pengalaman kerja, dan prestasi kerja.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}><strong style={{boxSizing: 'inherit', fontWeight: 'bolder'}}>Baca Juga :&nbsp;</strong><a href="https://pintek.id/blog/produktivitas-kerja-karyawan/" rel="noopener noreferrer" style={{boxSizing: 'inherit', backgroundColor: 'transparent', color: 'rgb(43, 64, 152)', textDecoration: 'none'}} target="_blank" title="Cara Ampuh untuk Meningkatkan Produktivitas Kerja Karyawan">Cara Ampuh untuk Meningkatkan Produktivitas Kerja Karyawan</a></p>
  <h3 style={{boxSizing: 'inherit', marginTop: 0, fontWeight: 700, fontSize: '1.722em', lineHeight: '1.258em', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>4. Buat CV yang Kreatif</h3>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Sekarang ini, bentuk CV yang umum digunakan menggunakan desain semacam infografis. Saking populernya, sudah ada banyak platform yang menyediakan layanan desain CV online atau download template CV.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Canva adalah salah satu platform yang paling populer digunakan karena cara membuat CV di Canva sangat sederhana dan mudah dipahami orang awam.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Namun, selain menggunakan template desain yang sudah umum, kamu bisa berkreasi dengan lebih kreatif dan membuat CV dalam berbagai desain bahkan bentuk.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Beberapa contoh CV kreatif misalnya CV yang ditampilkan dalam 1 halaman web, CV dalam bentuk video, CV yang berbentuk kemasan tertentu, dll.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>CV kreatif semacam ini akan membuat HRD langsung melirik CV mu.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Jika kamu mendaftar di pekerjaan yang tidak berbasis kreativitas, jangan terlalu ekstrim melakukan eksplorasi pembuatan CV. Kamu bisa membuat dalam bentuk umum, tapi desainnya dibuat lebih unik dibanding kebanyakan CV.</p>
  <h3 style={{boxSizing: 'inherit', marginTop: 0, fontWeight: 700, fontSize: '1.722em', lineHeight: '1.258em', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>5. Menggunakan Jasa Profesional</h3>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Sekarang ini mulai banyak penyedia jasa pembuatan CV di Jakarta, Bekasi, Yogyakarta, dan berbagai daerah lainnya di Indonesia. Jasa profesional ini bahkan bisa Pinters dapatkan secara online.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Jasa profesional ini biasanya melayani desain hingga konsultasi mengenai isi CV yang baik.</p>
  <p style={{boxSizing: 'inherit', marginBottom: '1.5em', marginTop: 0, color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}>Semoga ulasan tentang cara membuat CV di atas bisa sedikit membantu. Selamat mencoba dan semoga kamu bisa mendapatkan pekerjaan impianmu.</p>
  <div className="addtoany_share_save_container addtoany_content addtoany_content_bottom" style={{boxSizing: 'inherit', clear: 'both', margin: '16px auto', color: 'rgb(0, 0, 0)', fontFamily: 'Montserrat', fontSize: 14, fontStyle: 'normal', fontVariantLigatures: 'normal', fontVariantCaps: 'normal', fontWeight: 400, letterSpacing: 'normal', orphans: 2, textAlign: 'start', textIndent: 0, textTransform: 'none', whiteSpace: 'normal', widows: 2, wordSpacing: 0, WebkitTextStrokeWidth: 0, backgroundColor: 'rgb(255, 255, 255)', textDecorationThickness: 'initial', textDecorationStyle: 'initial', textDecorationColor: 'initial'}}><br className="Apple-interchange-newline" /></div>
</div>


          
        </div>
      </div>
    </>
  )
}

export default InfoPelatihan

